project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/
      - icon: envelope-at
        href: mailto:rujirawatpata@gmail.com
format:
  html:
    theme: sandstone
    css: styles.css



