---
title: Course Design and Assessment Design
---
::: {.callout-note}
Some innovative evidence-based course designs.
:::

# Course Design with Transparency in Learning and Teaching

- This [syllbus](Syllabus%20for%20Spring%202022%20MATH-1100-001.pdf) sample and [learning outcomes](Learning%20Targets_Outcomes%20for%20Exams_%20Sp20%20MATH%201050%20CBE%20Build.pdf) provides clear learning outcomes and expectations for student to be success in class. 
- This [rubric sample](CCAP_MATH_1100_for_Graders__shared_.pdf) was developed for graders to make the grading process transparency and consistency.

# Partially-Flipped Class using Class Prep assignments

- Students completed class assignments before classes to allow them to learn them at their own pace and focus on key concepts while they used class time that is dedicate to hands-on problem-solving activities that reinforce understanding and application of concepts.

<iframe width="560" height="315" src="https://www.youtube.com/embed/JSAnABPj4MA?si=3AAVvsxiG3tm0dDO" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

# Formative Assessment with Top Hat

Regular assessment to ensures that fundamental concepts are understood, allowing for timely instructional adjustments

<iframe width="560" height="315" src="https://www.youtube.com/embed/AqwnwbuNYMY?si=OLmopQqMg7pqvuiP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
